services:

    hack23-1-database:
        image: hack23-1-database
        build: ./database
        environment:
            POSTGRES_HOST_AUTH_METHOD: trust

    hack23-1-api:
        links:
            - hack23-1-database
       
        image: hack23-1-api
        ports:
            - 8002:8002
        build: ./api
        restart: always