"""add refrest_token system

Revision ID: 6c69a7cb8594
Revises: b99f25bba66e
Create Date: 2023-11-19 09:21:10.344242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c69a7cb8594'
down_revision = 'b99f25bba66e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_token_storage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('refresh_token', sa.TEXT(), nullable=True),
    sa.Column('expired', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('refresh_token_storage')
    # ### end Alembic commands ###
