"""add expedition field to user model

Revision ID: b99f25bba66e
Revises: 2ffb146477b3
Create Date: 2023-11-19 09:02:40.229584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b99f25bba66e'
down_revision = '2ffb146477b3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('expedition', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client', 'expedition')
    # ### end Alembic commands ###
